import 'package:flutter/material.dart';
import 'package:flutter/material.dart';
import 'screens/main_menu_screen.dart';
import 'dart:async';
import 'package:sqflite/sqflite.dart';
import 'package:path/path.dart';
import 'package:intl/intl.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter_native_timezone/flutter_native_timezone.dart';
import 'package:simp/notification.dart';
import 'package:timezone/data/latest.dart' 
import 'package:timezone/timezone.dart'